# stage 1
FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_PROXY_PORT VITE_HOST_ADDRESS

COPY package*.json ./

RUN npm ci

COPY . .

RUN VITE_PROXY_PORT=${VITE_PROXY_PORT} VITE_HOST_ADDRESS=${VITE_HOST_ADDRESS} npm run build

# stage 2
FROM nginx:stable-alpine AS runner

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]