services:
    proxy:
        ports:
            - "${PROXY_PORT}:${PROXY_PORT}"
        volumes:
            - ./proxy/nginx-dev.conf:/etc/nginx/nginx.conf:ro
        stop_grace_period: 0s

    frontend:
        image: frontend-vite
        container_name: frontend-vite
        build:
            dockerfile: Dockerfile.vite
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - ./ssl:/app/ssl
        environment:
            - VITE_PROXY_PORT=${PROXY_PORT}
            - VITE_HOST_ADDRESS=${VITE_HOST_ADDRESS}
        stop_grace_period: 0s

    gateway:
        ports:
            - "${GATEWAY_PORT}:${GATEWAY_PORT}"
        stop_grace_period: 0s

    authentification:
        ports:
            - "${AUTHENTIFICATION_PORT}:${AUTHENTIFICATION_PORT}"
        stop_grace_period: 0s

    blockchain:
        ports:
            - "${BLOCKCHAIN_PORT}:${BLOCKCHAIN_PORT}"
        stop_grace_period: 0s

    database:
        ports:
            - "${DATABASE_PORT}:${DATABASE_PORT}"
        stop_grace_period: 0s

    game:
        ports:
            - "${GAME_PORT}:${GAME_PORT}"
        stop_grace_period: 0s

    matchmaking:
        ports:
            - "${MATCHMAKING_PORT}:${MATCHMAKING_PORT}"
        stop_grace_period: 0s

    tournament:
        ports:
            - "${TOURNAMENT_PORT}:${TOURNAMENT_PORT}"
        stop_grace_period: 0s

    websocket:
        ports:
            - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
        stop_grace_period: 0s

    ai:
        ports:
            - "${AI_PORT}:${AI_PORT}"
        stop_grace_period: 0s
