services:
    proxy:
        image: nginx:stable-alpine
        container_name: proxy
        ports:
            - "${PROXY_PORT}:${PROXY_PORT}"
        volumes:
            - ./proxy/nginx-prod.conf:/etc/nginx/nginx.conf:ro
            - ./ssl:/etc/nginx/certs:ro
        networks:
            - transcendence-network
        depends_on:
            - frontend
            - gateway

    frontend:
        image: frontend-nginx
        container_name: frontend-nginx
        build:
            context: ./frontend
            dockerfile: Dockerfile.nginx
            args:
                VITE_PROXY_PORT: ${PROXY_PORT}
                VITE_HOST_DOMAIN: ${HOST_DOMAIN}
                VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        volumes:
            - ./ssl:/app/ssl
        networks:
            - transcendence-network

    gateway:
        image: gateway
        container_name: gateway
        build:
            context: ./backend
            dockerfile: gateway/Dockerfile
        environment:
            - SERVICE_NAME=gateway
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${GATEWAY_PORT}
        depends_on:
            - authentification
            - blockchain
            - database
            - game
            - matchmaking
            - tournament
            - websocket
            - ai
            - frontend
        networks:
            - transcendence-network

    authentification:
        image: authentification
        container_name: authentification
        build:
            context: ./backend/authentification
            dockerfile: Dockerfile
        environment:
            - SERVICE_NAME=authentification
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${AUTHENTIFICATION_PORT}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - JWT_SECRET=${JWT_SECRET}
        networks:
            - transcendence-network

    blockchain:
        image: blockchain
        container_name: blockchain
        build:
            context: ./backend/blockchain
            dockerfile: Dockerfile
        environment:
            - SERVICE_NAME=blockchain
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${BLOCKCHAIN_PORT}
        env_file:
            - .env
        networks:
            - transcendence-network

    database:
        image: database
        container_name: database
        build:
            context: ./backend
            dockerfile: database/Dockerfile
        environment:
            - SERVICE_NAME=database
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${DATABASE_PORT}
        networks:
            - transcendence-network
        volumes:
            - ./backend/database/db_data:/app/db_data

    game:
        image: game
        container_name: game
        build:
            context: ./backend
            dockerfile: game/Dockerfile
        environment:
            - SERVICE_NAME=game
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${GAME_PORT}
        networks:
            - transcendence-network

    matchmaking:
        image: matchmaking
        container_name: matchmaking
        build:
            context: ./backend
            dockerfile: matchmaking/Dockerfile
        environment:
            - SERVICE_NAME=matchmaking
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${MATCHMAKING_PORT}
        networks:
            - transcendence-network

    tournament:
        image: tournament
        container_name: tournament
        build:
            context: ./backend
            dockerfile: tournament/Dockerfile
        environment:
            - SERVICE_NAME=tournament
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${TOURNAMENT_PORT}
        networks:
            - transcendence-network

    websocket:
        image: websocket
        container_name: websocket
        build:
            context: ./backend
            dockerfile: websocket/Dockerfile
        environment:
            - SERVICE_NAME=websocket
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${WEBSOCKET_PORT}
        networks:
            - transcendence-network

    ai:
        image: ai
        container_name: ai
        build:
            context: ./backend
            dockerfile: ai/Dockerfile
        environment:
            - SERVICE_NAME=ai
            - NODE_ENV=${NODE_ENV}
            - HOST_IP=${HOST_IP}
            - PORT=${AI_PORT}
        networks:
            - transcendence-network

networks:
    transcendence-network:
        driver: bridge
