services:

  gateway:
    build: ./backend/gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/gateway:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - authentification
    networks:
      - transcendence-network

  authentification:
    build: ./backend/authentification
    networks:
      - transcendence-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - gateway
    networks:
      - transcendence-network

networks:
  transcendence-network:
    driver: bridge
