CREATE TABLE IF NOT EXISTS `users` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`username` TEXT UNIQUE NOT NULL,
	`password` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `tournaments` (
	`id` INTEGER PRIMARY KEY,
	`data` TEXT NOT NULL
);
